spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbdemo
    username: root
    password: MySQL
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: false